package com.seongmin.redislab.fault;

/** 허용된 장애 시나리오. 이 목록 밖의 동작은 API 로 실행할 수 없다. */
public enum FaultScenario {
	STOP_PRIMARY, KILL_PRIMARY, PAUSE_PRIMARY, STOP_REPLICA, KILL_REPLICA, STOP_SENTINEL, STOP_ALL_SENTINELS, STOP_PRIMARY_AND_ITS_REPLICA,
	RESTORE_NODE, RESTORE_ALL,
	PARTITION_PRIMARY_FROM_SENTINELS, PARTITION_PRIMARY_FROM_REPLICAS, PARTITION_PRIMARY_FROM_APP, PARTITION_PRIMARY_FROM_PEERS,
	NETEM_REPLICATION_DELAY, NETEM_GLOBAL_DELAY, NETEM_LOSS,
	TOXIC_APP_SENTINEL_TIMEOUT, TOXIC_APP_SENTINEL_LATENCY, REMOVE_TOXICS, CLEAR_NETWORK_FAULTS,
	// 복합 시나리오(실험 D/E/F): 선행 장애 뒤 Primary 를 죽인다. T0 는 마지막 단계(Primary kill) 시각.
	KILL_REPLICA_THEN_PRIMARY, KILL_ALL_REPLICAS_THEN_PRIMARY, STOP_SENTINELS_THEN_KILL_PRIMARY, KILL_TWO_PRIMARIES, NETEM_REPLICATION_DELAY_THEN_KILL_PRIMARY;

	public boolean isRestore() { return this == RESTORE_NODE || this == RESTORE_ALL || this == REMOVE_TOXICS || this == CLEAR_NETWORK_FAULTS; }
}
