#!/usr/bin/env bash
# 장애 시나리오 매트릭스: Cluster → Sentinel, 각 5회. 결과는 results/faults/.
set -uo pipefail
cd "$(dirname "$0")/.."
export RPS=${RPS:-300} WARM=10 STEADY=30 FAULT=40 RECOVER=40
CLUSTER="KILL_PRIMARY STOP_PRIMARY PAUSE_PRIMARY PARTITION_PRIMARY_FROM_PEERS PARTITION_PRIMARY_FROM_APP NETEM_GLOBAL_DELAY NETEM_LOSS KILL_REPLICA_THEN_PRIMARY KILL_TWO_PRIMARIES NETEM_REPLICATION_DELAY_THEN_KILL_PRIMARY STOP_PRIMARY_AND_ITS_REPLICA"
SENTINEL="KILL_PRIMARY STOP_PRIMARY PAUSE_PRIMARY PARTITION_PRIMARY_FROM_SENTINELS PARTITION_PRIMARY_FROM_REPLICAS PARTITION_PRIMARY_FROM_APP NETEM_GLOBAL_DELAY NETEM_LOSS KILL_REPLICA_THEN_PRIMARY KILL_ALL_REPLICAS_THEN_PRIMARY STOP_SENTINELS_THEN_KILL_PRIMARY STOP_ALL_SENTINELS NETEM_REPLICATION_DELAY_THEN_KILL_PRIMARY"
REPS=${REPS:-5}
echo "[$(date +%T)] === cluster faults ==="
bench/switch.sh cluster
bench/batch.sh faults "$REPS" $CLUSTER
echo "[$(date +%T)] === sentinel faults ==="
bench/switch.sh sentinel
bench/batch.sh faults "$REPS" $SENTINEL
echo "[$(date +%T)] === all-faults done ==="
